"""
Configuration for creating a new environment
"""

# Data for building initial class definitions
# 0 = class name
# 1 = True if class has Python class of same name
# 2 = cache variable name
# 3 = superclass cache variable name
# 4 = True if object is fixed size
# 5 = tuple of instance variable names
# 6 = tuple of class variable names
# 7 = tuple of shared pool names

Init_Class = (
    ("Object", True, "object", None, False, (), ("Dependencies", "FinalizableObjects"), ("VMPrimitives",)),
    ("UndefinedObject", True, "undef_obj", "object", True, (), (), ()),
    ("Boolean", False, "boolean", "object", True, (), (), ()),
    ("False", False, "false", "boolean", True, ("truthValue",), (), ()),
    ("True", False, "true", "boolean", True, ("truthValue",), (), ()),
    ("Exception", False, "exception", "object", True, ("creator", "tag", "messageText", "resumeBlock", "onDoBlock", "handlerBlock", "context", "isNested", "previousState"), ("NoTag",), ()),
    ("UnhandledException", False, "unhandled_except", "exception", True, ("originalException",), (), ()),
    ("Error", False, "error", "exception", True, (), (), ()),
    ("Notification", False, "notification", "exception", True, (), (), ()),
    ("MessageNotUnderstood", False, "msg_not_under", "error", True, ("message", "receiver"), (), ()),
    ("ArithmeticError", False, "arith_error", "error", True, (), (), ()),
    ("VMError", False, "vm_error", "error", True, (), (), ()),
    ("InvalidValue", False, "invalid_value", "error", True, ("value",), (), ()),
    ("NotIndexable", False, "not_indexable", "invalid_value", True, (), (), ()),
    ("ReadOnlyObject", False, "read_only_obj", "invalid_value", True, (), (), ()),
    ("WrongClass", False, "wrong_class", "invalid_value", True, ("validClasses",), (), ()),
    ("EmptyCollection", False, "empty_coll", "invalid_value", True, (), (), ()),
    ("InvalidArgument", False, "invalid_arg", "invalid_value", True, (), (), ()),
    ("ArgumentOutOfRange", False, "arg_range", "invalid_arg", True, ("low", "high"), (), ()),
    ("IndexOutOfRange", False, "index_range", "arg_range", True, ("collection",), (), ()),
    ("NotFound", False, "not_found", "invalid_arg", True, (), (), ()),
    ("ZeroDivide", False, "zero_divide", "arith_error", True, ("dividend",), (), ()),
    ("PrimitiveFailed", False, "primitive_fail", "vm_error", True, (), (), ()),
    ("WrongArgumentCount", False, "wrong_arg_count", "primitive_fail", True, (), (), ()),
    ("FileError", False, "file_error", "primitive_fail", True, (), (), ()),
    ("EndOfStream", False, "end_of_stream", "notification", True, ("stream",), (), ()),
    ("Message", True, "message", "object", True, ("selector", "args"), (), ()),
    ("Behavior", False, "behavior", "object", True, ("superClass", "methodDictionary", "instanceSpec", "subClasses", "instanceVariables"), (), ()), 
    ("ClassDescription", False, "class_desc", "behavior", True, (), (), ()),
    ("Class", True, "class", "class_desc", True, ("name", "comment", "category", "environment", "classVariables", "sharedPools", "pragmaHandlers"), (), ()),
    ("Metaclass", True, "metaclass", "class_desc", True, ("instanceClass",), (), ()),
    ("Iterable", False, "iterable", "object", True, (), (), ()),
    ("Collection", False, "collection", "iterable", True, (), (), ()),
    ("SequenceableCollection", False, "seq_collection", "collection", True, (), (), ()),
    ("ArrayedCollection", False, "arr_collection", "seq_collection", False, (), (), ()),
    ("OrderedCollection", False, "ord_collection", "seq_collection", False, ("firstIndex", "lastIndex"), (), ()),
    ("SortedCollection", False, "sort_collection", "ord_collection", False, ("lastOrdered", "sorted", "sortBlock"), (), ()),
    ("Array", True, "array", "arr_collection", False, (), (), ()),
    ("ByteArray", True, "bytearray", "arr_collection", False, (), (), ()),
    ("Link", False, "link", "object", True, ("nextLink",), (), ()),
    ("SymLink", True, "sym_link", "link", True, ("symbol",), (), ()),
    ("HashedCollection", False, "hash_collection", "collection", False, ("tally",), (), ()),
    ("Set", False, "set", "hash_collection", False, (), (), ()),
    ("Dictionary", True, "dictionary", "hash_collection", False, (), (), ()),
    ("BindingDictionary", True, "bind_dictionary", "dictionary", False, ("environment",), (), ()),
    ("AbstractNamespace", False, "abs_namespace", "bind_dictionary", False, ("name", "subspaces", "sharedPools"), (), ()),
    ("Namespace", True, "namespace", "abs_namespace", False, (), ("Current",), ()),
    ("RootNamespace", False, "root_namespace", "abs_namespace", False, (), (), ()),
    ("SystemDictionary", False, "sys_dictionary", "root_namespace", False, (), (), ()),
    ("Magnitude", False, "magnitude", "object", True, (), (), ()),
    ("LookupKey", False, "lookup_key", "magnitude", True, ("key",), (), ()),
    ("Association", True, "assoc", "lookup_key", True, ("value",), (), ()),
    ("HomedAssociation", False, "homed_assoc", "assoc", True, ("environment",), (), ()),
    ("VariableBinding", True, "variable_bind", "homed_assoc", True, (), (), ()),
    ("CharacterArray", False, "char_array", "arr_collection", False, (), (), ()),
    ("String", True, "string", "char_array", False, (), (), ()),
    ("Symbol", True, "symbol", "string", False, (), (), ()),
    ("Stream", False, "stream", "iterable", True, (), (), ()),
    ("PositionableStream", False, "pos_stream", "stream", True, ("collection", "ptr", "endPtr", "access"), (), ()),
    ("ReadStream", False, "read_stream", "pos_stream", True, (), (), ()),
    ("WriteStream", False, "write_stream", "pos_stream", True, (), (), ()),
    ("ReadWriteStream", False, "rw_stream", "write_stream", True, (), (), ()),
    ("FilePath", False, "file_path", "object", True, (), (), ()),
    ("File", False, "file", "file_path", True, ("path", "stat", "isSymbolicLink"), ("Epoch",), ()),
    ("Stat", False, "stat", "object", True, ("stMode", "stSize", "stAtime", "stMtime", "stCtime"), (), ()),
    ("Directory", False, "directory", "object", True, (), (), ()),
    ("FileDescriptor", False, "file_desc", "stream", True, ("access", "fd", "file", "isPipe", "atEnd", "peek"), ("AllOpenFiles",), ()),
    ("FileStream", True, "file_stream", "file_desc", True, ("collection", "ptr", "endPtr", "writePtr", "writeEnd"), ("Verbose", "Record", "Includes"), ()),
    ("TextCollector", False, "text_collect", "stream", True, ("receiver", "selector"), (), ()),
    ("Number", False, "number", "magnitude", True, (), (), ()),
    ("Integer", False, "integer", "number", True, (), (), ("PySymbols",)),
    ("SmallInteger", False, "small_int", "integer", True, (), (), ()),
    ("LargeInteger", False, "large_int", "integer", False, (), ("Zero", "One", "ZeroBytes", "OneBytes", "LeadingZeros", "TrailingZeros"), ()),
    ("LargePositiveInteger", True, "large_pos_int", "large_int", False, (), (), ()),
    ("LargeNegativeInteger", True, "large_neg_int", "large_int", False, (), (), ()),
    ("LargeZeroInteger", True, "large_zero_int", "large_pos_int", False, (), (), ()),
    ("Fraction", True, "fraction", "number", True, ("numerator", "denominator"), ("Zero", "One"), ()),
    ("Float", False, "float", "number", True, (), (), ()),
    ("FloatD", False, "float_d", "float", True, (), (), ()),
    ("FloatE", True, "float_e", "float", False, (), (), ()),
    ("Character", True, "character", "magnitude", True, ("codePoint",), ("Table", "UpperTable", "LowerTable"), ()),
    ("Time", False, "time", "magnitude", True, ("seconds",), ("SecondClockAdjustment", "ClockOnStartup", "ClockOnImageSave"), ()),
    ("Duration", False, "duration", "time", True, (), ("Zero",), ()),
    ("Date", False, "date", "magnitude", True, ("days", "day", "month", "year"), ("DayNameDict", "MonthNameDict"), ()),
    ("DateTime", False, "date_time", "date", True, ("seconds", "offset"), ("ClockPrecision",), (), ()),
    ("ContextPart", False, "context_part", "object", False, ("parent", "nativeIP", "ip", "sp", "receiver", "method"), (), ()),
    ("BlockContext", True, "blk_context", "context_part", False, ("outerContext",), (), ()),
    ("MethodContext", True, "meth_context", "context_part", False, ("flags",), (), ()),
    ("BlockClosure", True, "blk_closure", "object", True, ("outerContext", "block", "receiver"), (), ()),
    ("CompiledCode", False, "comp_code", "arr_collection", False, ("literals", "header"), (), ()),
    ("CompiledMethod", True, "comp_method", "comp_code", False, ("descriptor",), (), ()),
    ("CompiledBlock", True, "comp_block", "comp_code", False, ("method",), (), ()),
    ("MethodInfo", True, "meth_info", "object", False, ("sourceCode", "category", "class", "selector", "debugInfo"), (), ()),
    ("IdentitySet", False, "ident_set", "set", False, (), (), ()),
    ("LookupTable", False, "lookup_table", "dictionary", False, (), (), ()),
    ("IdentityDictionary", False, "ident_dictionary", "lookup_table", False, (), (), ()),
    ("MethodDictionary", True, "meth_dictionary", "ident_dictionary", False, ("mutex",), (), ()),
    ("WeakArray", False, "weak_array", "array", False, ("values", "nilValues"), (), ()),
    ("WeakSet", False, "weak_set", "set", False, (), (), ()),
    ("WeakIdentitySet", False, "weak_ident_set", "weak_set", False, (), (), ()),
    ("WeakKeyDictionary", False, "weak_key_dict", "dictionary", False, ("keys",), (), ()),
    ("WeakKeyIdentityDictionary", False, "weak_key_ident_dict", "weak_key_dict", False, (), (), ()),
    ("SymbolTableArray", True, "symbol_table", "array", False, (), (), ()),
    ("ObjectMemory", False, "object_memory", "object", True, ("numObject", "numMethodSlab", "numBlockSlab"), (), ()),
    ("TestSuite", False, "test", "object", True, ("testInst1", "testInst2"), ("TestClassVar",), ()),
)

# the instance variable names for Metaclass
# these end up as the instance variables for Class 
# and Metaclass instances
Init_Meta_Vars = ("superClass", "methodDictionary", "instanceSpec", "subClasses", "instanceVariables", 
                  "name", "comment", "category", "environment", "classVariables", "sharedPools", "pragmaHandlers")
                  

# the list of Smalltalk source modules that need compiled for rebuild
Init_Kernel_Mod = (
    "Object.st",
    "UndefObject.st",
    "Boolean.st",
    "False.st",
    "True.st",
    "BlkClosure.st",
    "ContextPart.st",
    "BlkContext.st",
    "MthContext.st",
    "Message.st",
    "ExcHandling.st",
    "UnhandledExcept.st",
    "Error.st",
    "Notification.st",
    "MsgNotUnderstood.st",
    "ArithError.st",
    "VMError.st",
    "InvalidValue.st",
    "NotIndexable.st",
    "ReadOnlyObj.st",
    "WrongClass.st",
    "EmptyColl.st",
    "InvalidArg.st",
    "ArgRange.st",
    "IndexRange.st",
    "NotFound.st",
    "ZeroDivide.st",
    "PrimFailed.st",
    "WrongArgCount.st",
    "FileError.st",
    "EndOfStream.st",
    "LookupKey.st",
    "Association.st",
    "HomedAssoc.st",
    "VarBinding.st",
    "Link.st",
    "SymLink.st",
    "Behavior.st",
    "ClassDesc.st",
    "Class.st",
    "Metaclass.st",
    "Magnitude.st",
    "Character.st",
    "Time.st",
    "Duration.st",
    "Date.st",
    "AnsiDates.st",
    "Number.st",
    "Integer.st",
    "SmallInt.st",
    "LargeInt.st",
    "LargePosInt.st",
    "LargeNegInt.st",
    "LargeZeroInt.st",
    "Fraction.st",
    "Float.st",
    "FloatD.st",
    "FloatE.st",
    "Iterable.st",
    "Collection.st",
    "SeqCollect.st",
    "HashedColl.st",
    "OrderColl.st",
    "SortCollect.st",
    "ArrayColl.st",
    "Array.st",
    "ByteArray.st",
    "CharArray.st",
    "String.st",
    "Symbol.st",
    "Set.st",
    "IdentitySet.st",
    "Dictionary.st",
    "LookupTable.st",
    "IdentDict.st",
    "BindingDict.st",
    "AbstNamespc.st",
    "Namespace.st",
    "WeakArray.st",
    "WeakSet.st",
    "WeakIdentSet.st",
    "WeakKeyDict.st",
    "WeakKeyIdentDict.st",
    "Stream.st",
    "PosStream.st",
    "ReadStream.st",
    "WriteStream.st",
    "RWStream.st",
    "FilePath.st",
    "File.st",
    "Stat.st",
    "Directory.st",
    "FileDescr.st",
    "FileStream.st",
    "Transcript.st",
    "CompildCode.st",
    "CompiledBlk.st",
    "CompildMeth.st",
    "MethodInfo.st",
    "ObjMemory.st",
    "TestSuite.st",
)

# the list of classes whose 'initialize' message
# should be sent at startup
Init_Class_Init = (
    "Object",
    "Character",
    "LargeInteger",
    "Fraction",
    "Time",
    "Duration",
    "Date",
    "DateTime",
    "File",
    "FileDescriptor",
    "FileStream",
)

# the list of primitive ops handled by the interpreter
# the primitive ID is the index of the name in the list
# plus 1 (0 is reserved)
Init_Primitive = (
    "Object_basicSize",
    "Object_identity",
    "Object_class",
    "Object_basicAt",
    "Object_basicAtPut",
    "Object_shallowCopy",
    "Object_isReadOnly",
    "Object_hash",
    "Object_become",
    "Object_allOwners",
    "Object_perform",
    "Object_performWithArguments",
    "Object_makeWeak",
    "Object_makeEphemeron",
    "Object_instVarAt",
    "Object_instVarAtPut",
    "BlockClosure_value",
    "BlockClosure_cull",
    "BlockClosure_valueWithArguments",
    "BlockClosure_valueAndResumeOnUnwind",
    "ContextPart_continue",
    "Behavior_basicNew",
    "Behavior_basicNewColon",
    "Behavior_newInitialize",
    "Behavior_newColonInitialize",
    "Character_create",
    "Character_equal",
    "SmallInteger_plus",
    "SmallInteger_minus",
    "SmallInteger_lt",
    "SmallInteger_gt",
    "SmallInteger_le",
    "SmallInteger_ge",
    "SmallInteger_eq",
    "SmallInteger_ne",
    "SmallInteger_times",
    "SmallInteger_intDiv",
    "SmallInteger_modulo",
    "SmallInteger_quo",
    "SmallInteger_divide",
    "SmallInteger_bitAnd",
    "SmallInteger_bitOr",
    "SmallInteger_bitXor",
    "SmallInteger_bitShift",
    "SmallInteger_asFloatD",
    "SmallInteger_asFloatE",
    "SmallInteger_scramble",
    "LargeInteger_lt",
    "LargeInteger_gt",
    "LargeInteger_le",
    "LargeInteger_ge",
    "LargeInteger_eq",
    "LargeInteger_ne",
    "LargeInteger_plus",
    "LargeInteger_minus",
    "LargeInteger_times",
    "LargeInteger_intDiv",
    "LargeInteger_modulo",
    "LargeInteger_negated",
    "LargeInteger_bitAnd",
    "LargeInteger_bitOr",
    "LargeInteger_bitXor",
    "LargeInteger_bitShift",
    "LargeInteger_bitInvert",
    "LargeInteger_asFloatD",
    "LargeInteger_hash",
    "LargePositiveInteger_basicNewColon",
    "LargeNegativeInteger_basicNewColon",
    "LargeZeroInteger_basicNewColon",
    "Float_primHash",
    "Float_sin",
    "Float_cos",
    "Float_tan",
    "Float_arcSin",
    "Float_arcCos",
    "Float_arcTan",
    "Float_exp",
    "Float_ln",
    "Float_sqrt",
    "Float_pow",
    "Float_ceil",
    "Float_floor",
    "FloatD_fromBytes",
    "FloatD_infinity",
    "FloatD_negativeInfinity",
    "FloatD_nan",
    "FloatD_fmax",
    "FloatD_fminNormalized",
    "FloatD_emax",
    "FloatD_emin",
    "FloatD_precision",
    "FloatD_decimalDigits",
    "FloatD_asBytes",
    "FloatD_plus",
    "FloatD_minus",
    "FloatD_times",
    "FloatD_divide",
    "FloatD_lt",
    "FloatD_gt",
    "FloatD_le",
    "FloatD_ge",
    "FloatD_eq",
    "FloatD_ne",
    "FloatD_asFloatE",
    "FloatD_truncated",
    "FloatD_exponent",
    "FloatD_fractionPart",
    "FloatD_timesTwoPower",
    "FloatE_fromBytes",
    "FloatE_infinity",
    "FloatE_negativeInfinity",
    "FloatE_nan",
    "FloatE_plus",
    "FloatE_minus",
    "FloatE_times",
    "FloatE_divide",
    "FloatE_lt",
    "FloatE_gt",
    "FloatE_le",
    "FloatE_ge",
    "FloatE_eq",
    "FloatE_ne",
    "FloatE_asFloatD",
    "FloatE_fractionPart",
    "FloatE_truncated",
    "FloatE_exponent",
    "Time_secondClock",
    "Time_nanosecondClock",
    "Time_timezoneBias",
    "Time_timezone",
    "ArrayedCollection_replaceFromToWithStartingAt",
    "ArrayedCollection_indexOfStartingAt",
    "ArrayedCollection_equal",
    "CharacterArray_valueAt",
    "CharacterArray_valueAtPut",
    "ByteArray_basicNewColon",
    "ByteArray_newColonInitialize",
    "ByteArray_replaceFromToWithStringStartingAt",
    "ByteArray_indexOfStartingAt",
    "ByteArray_equal",
    "String_replaceFromToWithByteArrayStartingAt",
    "String_hash",
    "Symbol_intern",
    "File_errno",
    "File_strerror",
    "File_lstat",
    "File_isRead",
    "File_isWrite",
    "File_isExe",
    "Direcotry_getcwd",
    "FileDescriptor_fileOp",
    "ObjectMemory_update",
)
