
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN BASENUMBER CARET DECNUMBER DSTRING FLTNUMBER IDENT LBRACK LPARENS MESSAGEARG OPERATOR PERIOD PIPE RBRACK RPARENS SSTRINGstatement : exec_statement\n                  | return_statementreturn_statement : CARET exec_statementexec_statement : unary_message\n                       | literalunary_message : literal IDENTliteral : IDENT\n                | DECNUMBER'
    
_lr_action_items = {'CARET':([0,],[6,]),'IDENT':([0,5,6,7,8,],[7,9,7,-7,-8,]),'DECNUMBER':([0,6,],[8,8,]),'$end':([1,2,3,4,5,7,8,9,10,],[0,-1,-2,-4,-5,-7,-8,-6,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'exec_statement':([0,6,],[2,10,]),'return_statement':([0,],[3,]),'unary_message':([0,6,],[4,4,]),'literal':([0,6,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> exec_statement','statement',1,'p_statement','sparser.py',28),
  ('statement -> return_statement','statement',1,'p_statement','sparser.py',29),
  ('return_statement -> CARET exec_statement','return_statement',2,'p_return_statement','sparser.py',33),
  ('exec_statement -> unary_message','exec_statement',1,'p_exec_statement','sparser.py',37),
  ('exec_statement -> literal','exec_statement',1,'p_exec_statement','sparser.py',38),
  ('unary_message -> literal IDENT','unary_message',2,'p_unary_message','sparser.py',42),
  ('literal -> IDENT','literal',1,'p_literal','sparser.py',46),
  ('literal -> DECNUMBER','literal',1,'p_literal','sparser.py',47),
]
